name: test_zyneventures
description: Flutter app.

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  http: ^1.2.2
  intl: ^0.19.0
  firebase_core: ^2.31.0
  firebase_auth: ^4.17.8
  flutter_svg: ^2.0.10+1
  cloud_firestore: ^4.17.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
